include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    curly_braces_in_flow_control_structures: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    no_leading_underscores_for_local_identifiers: ignore
    avoid_print: ignore
    unused_field: ignore
