// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCXMo7dtaCbP7YxgfJomaBSyvI-L4j9g',
    appId: '1:508451456084:web:742c453808a194caff19c1',
    messagingSenderId: '508451456084',
    projectId: 'graduation-project-f3148',
    authDomain: 'graduation-project-f3148.firebaseapp.com',
    storageBucket: 'graduation-project-f3148.firebasestorage.app',
    measurementId: 'G-DBHRD0547C',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4P5QclUhf8cninjHqUtGeD78bKqwRysI',
    appId: '1:508451456084:android:0d3a3a075c9c0537ff19c1',
    messagingSenderId: '508451456084',
    projectId: 'graduation-project-f3148',
    storageBucket: 'graduation-project-f3148.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZyvoW5bVq8ALu_VUUy7o1aVvHLuQfanc',
    appId: '1:508451456084:ios:1ac26f008cabed27ff19c1',
    messagingSenderId: '508451456084',
    projectId: 'graduation-project-f3148',
    storageBucket: 'graduation-project-f3148.firebasestorage.app',
    iosBundleId: 'com.example.finalProject3',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJCXMo7dtaCbP7YxgfJomaBSyvI-L4j9g',
    appId: '1:508451456084:web:6621607fbd626193ff19c1',
    messagingSenderId: '508451456084',
    projectId: 'graduation-project-f3148',
    authDomain: 'graduation-project-f3148.firebaseapp.com',
    storageBucket: 'graduation-project-f3148.firebasestorage.app',
    measurementId: 'G-1V8HT22KHF',
  );
}
